# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/setuptools-40.2.0-python_2.7-on-linux_64, last modified Mon Aug 27 16:33:48 2018
# ------------------------------------------------

package:
    name: setuptools
    version: 40.2.0
source:
    patches:
        - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
        - 0002-disable-downloads-inside-conda-build.patch
    sha256: 47881d54ede4da9c15273bac65f9340f8929d4f0213193fa7894be384f2dcfa6
    url: https://pypi.io/packages/source/s/setuptools/setuptools-40.2.0.zip
build:
    entry_points:
        - easy_install = setuptools.command.easy_install:main
    number: '0'
    string: py27_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py27_1
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2p h14c3975_0
        - python 2.7.15 h1571d57_0
        - readline 7.0 ha6073c6_4
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - zlib 1.2.11 ha838bed_2
    run:
        - certifi >=2016.09
        - python >=2.7,<2.8.0a0
test:
    commands:
        - easy_install --help
    imports:
        - easy_install
        - pkg_resources
        - setuptools
about:
    description: 'Setuptools is a fully-featured, actively-maintained, and stable
        library

        designed to facilitate packaging Python projects.

        '
    dev_source_url: https://github.com/pypa/setuptools/tree/master/docs
    dev_url: https://github.com/pypa/setuptools
    doc_url: http://pythonhosted.org/setuptools/
    home: https://github.com/pypa/setuptools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Download, build, install, upgrade, and uninstall Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - nicoddemus
        - ocefpaf
