# This file created by conda-build 3.10.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/requests-2.19.1-python_2.7-on-linux_64, last modified Mon Jun 18 17:10:47 2018
# ------------------------------------------------

package:
    name: requests
    version: 2.19.1
source:
    sha256: ec22d826a36ed72a7358ff3fe56cbd4ba69dd7a6718ffd450ff0e9df7a47ce6a
    url: https://pypi.io/packages/source/r/requests/requests-2.19.1.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py27_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py27_0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2o h20670df_0
        - pip 10.0.1 py27_0
        - python 2.7.15 h1571d57_0
        - readline 7.0 ha6073c6_4
        - setuptools 39.2.0 py27_0
        - sqlite 3.23.1 he433501_0
        - tk 8.6.7 hc745277_3
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 ha838bed_2
    run:
        - certifi >=2017.4.17
        - chardet >=3.0.2,<3.1.0
        - idna >=2.5,<2.8
        - python >=2.7,<2.8.0a0
        - urllib3 >=1.21.1,<1.24
test:
    imports:
        - requests
about:
    description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

        consumption.

        '
    dev_url: https://github.com/kennethreitz/requests
    doc_source_url: https://github.com/requests/requests/tree/master/docs
    doc_url: http://docs.python-requests.org/
    home: http://python-requests.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Python HTTP for Humans.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - sigmavirus24
